INDEX_PATH = 'index/index.txt'
POSITIONAL_INDEX_PATH = 'index/positional_index.txt'
LITE_INDEX_PATH = 'index/lite_index.txt'
AUTHOR_INDEX_PATH = 'index/author_index.txt'
TITLE_INDEX_PATH = 'index/title_index.txt'